// PDF Template definitions for DompetKu
// Each template defines: style, theme, layout, sections, options

export type PdfTemplateId =
  | "minimal-clean"
  | "modern-gradient"
  | "corporate-formal"
  | "dark-mode"
  | "pastel-soft"
  | "vintage-paper"
  | "instagram-story"
  | "infographic"
  | "bank-statement"
  | "receipt-style"
  | "slip-transaksi"
  | "laporan-tahunan"
  | "laporan-pajak"
  | "laporan-budget"
  | "laporan-goals"
  | "laporan-hutang"
  | "laporan-akun"
  | "laporan-ortu"
  | "laporan-patungan"
  | "laporan-skripsi"
  | "laporan-semester"
  | "weekly-summary"
  | "cash-flow"
  | "net-worth"
  | "slip-jajan";

export interface PdfTemplate {
  id: PdfTemplateId;
  name: string;
  description: string;
  category: "style" | "report" | "audience" | "student";
  // Visual
  theme: {
    primary: string;
    secondary: string;
    accent: string;
    bg: string;
    text: string;
    textMuted: string;
    border: string;
    tableHeaderBg: string;
    tableHeaderText: string;
    tableStripe: string;
  };
  // Layout
  layout: {
    size: "A4" | "A5" | "LETTER" | [number, number]; // custom [w, h]
    orientation: "portrait" | "landscape";
    margin: number;
    fontSize: number;
    titleSize: number;
    coverPage: boolean;
    twoColumn: boolean;
  };
  // Sections to include (toggle)
  sections: {
    summary: boolean;
    categoryBreakdown: boolean;
    topMerchants: boolean;
    transactionList: boolean;
    charts: boolean;
    budgetVsActual: boolean;
    goalsProgress: boolean;
    insights: boolean;
    tips: boolean;
    watermark: boolean;
    footer: boolean;
  };
  // Options
  showBranding: boolean;
  showPageNumbers: boolean;
  showTimestamp: boolean;
  compactMode: boolean;
  emoji: string;
}

export const PDF_TEMPLATES: PdfTemplate[] = [
  // === STYLE TEMPLATES ===
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    description: "Putih dominan, garis tipis, profesional & modern",
    category: "style",
    theme: {
      primary: "#10b981",
      secondary: "#6b7280",
      accent: "#10b981",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      tableHeaderBg: "#10b981",
      tableHeaderText: "#ffffff",
      tableStripe: "#f9fafb",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "📋",
  },
  {
    id: "modern-gradient",
    name: "Modern Gradient",
    description: "Header gradient emerald, card-based, sesuai tema app",
    category: "style",
    theme: {
      primary: "#10b981",
      secondary: "#14b8a6",
      accent: "#06b6d4",
      bg: "#ffffff",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
      tableHeaderBg: "#10b981",
      tableHeaderText: "#ffffff",
      tableStripe: "#f0fdf4",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 40,
      fontSize: 10,
      titleSize: 24,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: true,
      transactionList: true,
      charts: true,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "✨",
  },
  {
    id: "corporate-formal",
    name: "Corporate Formal",
    description: "Border solid, footer page number, untuk laporan resmi",
    category: "style",
    theme: {
      primary: "#1e293b",
      secondary: "#475569",
      accent: "#0f172a",
      bg: "#ffffff",
      text: "#1e293b",
      textMuted: "#64748b",
      border: "#cbd5e1",
      tableHeaderBg: "#1e293b",
      tableHeaderText: "#ffffff",
      tableStripe: "#f1f5f9",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 60,
      fontSize: 9,
      titleSize: 18,
      coverPage: true,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "🏢",
  },
  {
    id: "dark-mode",
    name: "Dark Mode",
    description: "Background gelap, accent emerald, unik & modern",
    category: "style",
    theme: {
      primary: "#10b981",
      secondary: "#06b6d4",
      accent: "#8b5cf6",
      bg: "#0f172a",
      text: "#f1f5f9",
      textMuted: "#94a3b8",
      border: "#334155",
      tableHeaderBg: "#1e293b",
      tableHeaderText: "#10b981",
      tableStripe: "#1e293b",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 22,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: true,
      transactionList: true,
      charts: true,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "🌙",
  },
  {
    id: "pastel-soft",
    name: "Pastel Soft",
    description: "Warna pastel, rounded cards, friendly untuk personal",
    category: "style",
    theme: {
      primary: "#a7f3d0",
      secondary: "#fbcfe8",
      accent: "#bae6fd",
      bg: "#fefce8",
      text: "#374151",
      textMuted: "#9ca3af",
      border: "#fce7f3",
      tableHeaderBg: "#86efac",
      tableHeaderText: "#14532d",
      tableStripe: "#fef3c7",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 45,
      fontSize: 10,
      titleSize: 22,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: true,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: false,
    emoji: "🌸",
  },
  {
    id: "vintage-paper",
    name: "Vintage Paper",
    description: "Texture kertas, font serif, klasik & estetik",
    category: "style",
    theme: {
      primary: "#92400e",
      secondary: "#a16207",
      accent: "#78350f",
      bg: "#fef3c7",
      text: "#451a03",
      textMuted: "#92400e",
      border: "#d6b68c",
      tableHeaderBg: "#92400e",
      tableHeaderText: "#fef3c7",
      tableStripe: "#fde68a",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 55,
      fontSize: 10,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "📜",
  },
  {
    id: "infographic",
    name: "Infographic",
    description: "Visual-heavy: icons, charts besar, minimal tabel",
    category: "style",
    theme: {
      primary: "#10b981",
      secondary: "#f59e0b",
      accent: "#8b5cf6",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      tableHeaderBg: "#10b981",
      tableHeaderText: "#ffffff",
      tableStripe: "#f0fdf4",
    },
    layout: {
      size: "A4",
      orientation: "landscape",
      margin: 40,
      fontSize: 9,
      titleSize: 26,
      coverPage: false,
      twoColumn: true,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: true,
      transactionList: false,
      charts: true,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: true,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: false,
    emoji: "📊",
  },
  {
    id: "bank-statement",
    name: "Bank Statement",
    description: "Mirip rekening koran: tabel rapat, monospace, saldo berjalan",
    category: "style",
    theme: {
      primary: "#1e40af",
      secondary: "#3b82f6",
      accent: "#2563eb",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#d1d5db",
      tableHeaderBg: "#1e40af",
      tableHeaderText: "#ffffff",
      tableStripe: "#eff6ff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 40,
      fontSize: 8,
      titleSize: 16,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: false,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: true,
    emoji: "🏦",
  },
  {
    id: "receipt-style",
    name: "Receipt Style",
    description: "Mirip struk: font monospace, border dashed, compact",
    category: "style",
    theme: {
      primary: "#111827",
      secondary: "#374151",
      accent: "#10b981",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#9ca3af",
      tableHeaderBg: "#f3f4f6",
      tableHeaderText: "#111827",
      tableStripe: "#ffffff",
    },
    layout: {
      size: [280, 600],
      orientation: "portrait",
      margin: 20,
      fontSize: 8,
      titleSize: 14,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: true,
    emoji: "🧾",
  },
  // === REPORT TEMPLATES ===
  {
    id: "slip-transaksi",
    name: "Slip Transaksi",
    description: "PDF 1 transaksi: nomor, tanggal, merchant, QR code",
    category: "report",
    theme: {
      primary: "#10b981",
      secondary: "#6b7280",
      accent: "#10b981",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      tableHeaderBg: "#10b981",
      tableHeaderText: "#ffffff",
      tableStripe: "#f9fafb",
    },
    layout: {
      size: "A5",
      orientation: "portrait",
      margin: 30,
      fontSize: 9,
      titleSize: 16,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: false,
    emoji: "🎫",
  },
  {
    id: "laporan-tahunan",
    name: "Laporan Tahunan",
    description: "12 bulan summary + tren tahunan + top categories",
    category: "report",
    theme: {
      primary: "#10b981",
      secondary: "#0891b2",
      accent: "#8b5cf6",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      tableHeaderBg: "#10b981",
      tableHeaderText: "#ffffff",
      tableStripe: "#f0fdf4",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 9,
      titleSize: 22,
      coverPage: true,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: true,
      transactionList: false,
      charts: true,
      budgetVsActual: false,
      goalsProgress: true,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "📅",
  },
  {
    id: "laporan-pajak",
    name: "Laporan Pajak",
    description: "Transaksi tax-deductible + business expense, format SPT",
    category: "report",
    theme: {
      primary: "#dc2626",
      secondary: "#991b1b",
      accent: "#7f1d1d",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#fecaca",
      tableHeaderBg: "#dc2626",
      tableHeaderText: "#ffffff",
      tableStripe: "#fef2f2",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 9,
      titleSize: 18,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: true,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "🧾",
  },
  {
    id: "laporan-budget",
    name: "Laporan Budget",
    description: "Budget vs actual per kategori, variance, recommendations",
    category: "report",
    theme: {
      primary: "#8b5cf6",
      secondary: "#a78bfa",
      accent: "#7c3aed",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e9d5ff",
      tableHeaderBg: "#8b5cf6",
      tableHeaderText: "#ffffff",
      tableStripe: "#faf5ff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 9,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: true,
      budgetVsActual: true,
      goalsProgress: false,
      insights: true,
      tips: true,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "📊",
  },
  {
    id: "laporan-goals",
    name: "Laporan Target",
    description: "Progress semua target tabungan + estimasi tanggal",
    category: "report",
    theme: {
      primary: "#22c55e",
      secondary: "#16a34a",
      accent: "#15803d",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#dcfce7",
      tableHeaderBg: "#22c55e",
      tableHeaderText: "#ffffff",
      tableStripe: "#f0fdf4",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: true,
      budgetVsActual: false,
      goalsProgress: true,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "🎯",
  },
  {
    id: "laporan-hutang",
    name: "Laporan Hutang",
    description: "Daftar hutang/piutang, jatuh tempo, status",
    category: "report",
    theme: {
      primary: "#f59e0b",
      secondary: "#d97706",
      accent: "#b45309",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#fef3c7",
      tableHeaderBg: "#f59e0b",
      tableHeaderText: "#ffffff",
      tableStripe: "#fffbeb",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "💳",
  },
  {
    id: "laporan-akun",
    name: "Laporan Akun",
    description: "Statement per akun: saldo awal, transaksi, saldo akhir",
    category: "report",
    theme: {
      primary: "#0891b2",
      secondary: "#0e7490",
      accent: "#155e75",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#cffafe",
      tableHeaderBg: "#0891b2",
      tableHeaderText: "#ffffff",
      tableStripe: "#ecfeff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 45,
      fontSize: 9,
      titleSize: 18,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: true,
    emoji: "🏛️",
  },
  {
    id: "cash-flow",
    name: "Cash Flow Statement",
    description: "Statement arus kas: operating/investing/financing",
    category: "report",
    theme: {
      primary: "#0f766e",
      secondary: "#115e59",
      accent: "#134e4a",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#ccfbf1",
      tableHeaderBg: "#0f766e",
      tableHeaderText: "#ffffff",
      tableStripe: "#f0fdfa",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 9,
      titleSize: 18,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: false,
      charts: true,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "💧",
  },
  {
    id: "net-worth",
    name: "Net Worth Report",
    description: "Total aset vs kewajiban, chart tren net worth",
    category: "report",
    theme: {
      primary: "#7c3aed",
      secondary: "#6d28d9",
      accent: "#5b21b6",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#ede9fe",
      tableHeaderBg: "#7c3aed",
      tableHeaderText: "#ffffff",
      tableStripe: "#f5f3ff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 22,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: true,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "💎",
  },
  // === AUDIENCE TEMPLATES ===
  {
    id: "laporan-ortu",
    name: "Laporan ke Ortu",
    description: "Format sederhana: uang saku, habis, sisa, pesan",
    category: "audience",
    theme: {
      primary: "#10b981",
      secondary: "#34d399",
      accent: "#059669",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#d1fae5",
      tableHeaderBg: "#10b981",
      tableHeaderText: "#ffffff",
      tableStripe: "#f0fdf4",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 11,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: false,
      charts: false,
      budgetVsActual: false,
      goalsProgress: true,
      insights: false,
      tips: true,
      watermark: false,
      footer: true,
    },
    showBranding: false,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: false,
    emoji: "👨‍👩‍👦",
  },
  // === STUDENT TEMPLATES ===
  {
    id: "laporan-patungan",
    name: "Laporan Patungan",
    description: "Split bill per orang, siapa bayar apa, siapa hutang",
    category: "student",
    theme: {
      primary: "#f97316",
      secondary: "#fb923c",
      accent: "#ea580c",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#fed7aa",
      tableHeaderBg: "#f97316",
      tableHeaderText: "#ffffff",
      tableStripe: "#fff7ed",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: false,
    emoji: "👥",
  },
  {
    id: "laporan-skripsi",
    name: "Laporan Skripsi",
    description: "Breakdown biaya skripsi per fase: proposal, survey, print",
    category: "student",
    theme: {
      primary: "#8b5cf6",
      secondary: "#a78bfa",
      accent: "#7c3aed",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e9d5ff",
      tableHeaderBg: "#8b5cf6",
      tableHeaderText: "#ffffff",
      tableStripe: "#faf5ff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 20,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "🎓",
  },
  {
    id: "laporan-semester",
    name: "Laporan Semester",
    description: "Total biaya per semester, breakdown per kategori",
    category: "student",
    theme: {
      primary: "#0891b2",
      secondary: "#06b6d4",
      accent: "#0e7490",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#cffafe",
      tableHeaderBg: "#0891b2",
      tableHeaderText: "#ffffff",
      tableStripe: "#ecfeff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 50,
      fontSize: 10,
      titleSize: 22,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: false,
      transactionList: false,
      charts: true,
      budgetVsActual: false,
      goalsProgress: true,
      insights: true,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: true,
    showTimestamp: true,
    compactMode: false,
    emoji: "📚",
  },
  {
    id: "weekly-summary",
    name: "Weekly Summary",
    description: "Ringkasan 7 hari: daily spending, top category, tips",
    category: "report",
    theme: {
      primary: "#06b6d4",
      secondary: "#22d3ee",
      accent: "#0891b2",
      bg: "#ffffff",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#cffafe",
      tableHeaderBg: "#06b6d4",
      tableHeaderText: "#ffffff",
      tableStripe: "#ecfeff",
    },
    layout: {
      size: "A4",
      orientation: "portrait",
      margin: 45,
      fontSize: 10,
      titleSize: 18,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: true,
      topMerchants: true,
      transactionList: true,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: true,
      tips: true,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: true,
    emoji: "📆",
  },
  {
    id: "slip-jajan",
    name: "Slip Jajan",
    description: "Struk jajan kecil (kopi/mie), cute design untuk mahasiswa",
    category: "student",
    theme: {
      primary: "#ec4899",
      secondary: "#f472b6",
      accent: "#db2777",
      bg: "#fffbeb",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#fbcfe8",
      tableHeaderBg: "#ec4899",
      tableHeaderText: "#ffffff",
      tableStripe: "#fdf2f8",
    },
    layout: {
      size: [280, 400],
      orientation: "portrait",
      margin: 20,
      fontSize: 9,
      titleSize: 14,
      coverPage: false,
      twoColumn: false,
    },
    sections: {
      summary: true,
      categoryBreakdown: false,
      topMerchants: false,
      transactionList: false,
      charts: false,
      budgetVsActual: false,
      goalsProgress: false,
      insights: false,
      tips: false,
      watermark: false,
      footer: true,
    },
    showBranding: true,
    showPageNumbers: false,
    showTimestamp: true,
    compactMode: true,
    emoji: "🍜",
  },
];

export const PDF_TEMPLATE_CATEGORIES = [
  { id: "style", label: "Gaya Tampilan", icon: "Palette" },
  { id: "report", label: "Tipe Laporan", icon: "FileText" },
  { id: "audience", label: "Untuk Siapa", icon: "Users" },
  { id: "student", label: "Mahasiswa", icon: "GraduationCap" },
] as const;
